
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'public/**/*'

# FIXME: Cop disabled as it Rubocop fails when enabling it. Enable it when the bug is solved.
# Checks for array literals made up of word-like strings, that are not using the %w() syntax.
Style/WordArray:
  Enabled: false
